Issue #3
Morvell/liquid-log pull request #2
Opened 2017-10-27 05:32 UTC by Morvell

Парсинг через web форму. Однако пока не реализована загрузка файла и TraceResult.
Все логи что есть на openshift парселись через web.  
http://wildfly-liquid-log-develop.148.251.87.70.nip.io/
@ykalemi @d0k1

2017-10-27 08:00 UTC, ykalemi requested changes

2017-10-27 08:00 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/ParserDate.java
> +    public Boolean getTraceResult() {
В целом, всё очень круто. Хорошо, что используете один объект для упаковки полей формы. Можно даже передавать его дальше в Parser, чтобы не усложнять сигнатуру. Но это пока не имеет значения.

Единственное замечание - метод getTraceResult не используется.

2017-10-27 08:00 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Parser.java
> +    public static boolean pars(String nameBD, String parserConf, String filePath, String timeZone) throws IOException, ParseException
тут опечатка, лучше - _parse_

2017-10-27 16:41 UTC, d0k1 commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +                File dir = new File(rootPath + File.separator + "tmpFiles");
Насколько мне известно в Java есть более прямой и простой путь получить каталог для временных файлов

2017-10-27 17:02 UTC, Morvell commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +                File dir = new File(rootPath + File.separator + "tmpFiles");
Это ещё только заготовка. И она в любом случае будет переделываться, ибо мне не нравится

2017-10-27 17:03 UTC, Morvell commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +                File dir = new File(rootPath + File.separator + "tmpFiles");
@d0k1
Это всего лишь заготовка, и она будет переделываться, ибо мне не нравится.

2017-10-27 19:30 UTC, merged

2017-10-28 02:38 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Parser.java
> +    public static boolean parse(String nameBD, String parserConf, File filePath, String timeZone) throws IOException, ParseException
поспешили с мерджем - traceResult у вас так и остался неиспользуемым и не передается в Parser