Issue #3 v2
Morvell/liquid-log pull request #3
Opened 2017-10-29 14:09 UTC by Morvell

Добавлено отображение логов, если выбрать такую опцию на странице парсинга. Убрана зависимость от параметров VM на локалке. Однако до сих пор не решена проблема с загрузкой файлов <1мб
http://wildfly-liquid-log-develop.148.251.87.70.nip.io/
@ykalemi @d0k1

2017-10-29 17:27 UTC, ykalemi requested changes
в целом хочу предложить отправлять на ревью изменения как-то более атомарно. Доделать одну задачу (парсинг через веб), потом приступать к другой - отображение лога в вебе (или вообще её пока отложить)

2017-10-29 17:27 UTC, ykalemi commented on pom.xml
> +            <version>1.2.2</version>
зачем понижать версию?

2017-10-29 17:27 UTC, ykalemi commented on pom.xml
> +            <version>2.1</version>
тут зачем-то понижена версия, а потом ниже добавлена ещё одна такая же зависимость

2017-10-29 17:27 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +            ArrayList<ActionDoneParser> date = new ArrayList<>();
Похвально, что вы хотите решить задачу отображения лога в GUI, но это решение мне видится слишком преждевременным. Впоследствии оно будет очень мешать вносить изменения.

Вы выносите на уровень GUI класс ActionDoneParser, который вообще говоря, занимается парсингом. Создаете его здесь ещё раз и ещё раз проводите вычисления. (при этом, как мы помним, у приложения вообще 3 режима парсинга, где ActionDoneParser - только один из. Значит, на двух других это просто не будет работать).
Далее в этот класс вы вводите два новых поля (что такое K? не очень читаемо) для того, чтобы отобразить это в интерфейсе.

2017-10-29 17:27 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +    public ParserController(InfluxDAO influxDAO){
Да, вот про это изменение я говорил. Можно оставить так, а можно пойти дальше - на самом деле в этом контроллере нам совсем не нужно DAO, мы его просто передаем дальше в Parser. Это значит, что `@Inject` должен быть уже в парсере, а сам парсер - спринг-бином.

2017-10-30 07:51 UTC, Morvell commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +            ArrayList<ActionDoneParser> date = new ArrayList<>();
@ykalemi Тогда я не совсем понимаю тз. Нужно было просто сделать отображение логов на КОНСОЛЬ во выбору пользователя?

2017-10-30 07:52 UTC, Morvell commented on pom.xml
> +            <version>2.1</version>
@ykalemi Не досмотрел

2017-10-30 07:53 UTC, Morvell commented on pom.xml
> +            <version>1.2.2</version>
@ykalemi Пытался решить проблему с загрузкой файлов

2017-10-30 09:30 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +            ArrayList<ActionDoneParser> date = new ArrayList<>();
ТЗ отдельно, решение - отдельно.

ТЗ придумали совместно, и оно звучало примерно так - то, что раньше писалось в консоль (а это был результат парсинга в виде csv), теперь выводить в браузер после загрузки и обработки файла.

Вопросы у меня не к т.з., а к реализации. Ещё раз:
- появилось дополнительное вычисление dones.calculate(), хотя это и так делается уже во время парсинга
- появились дополнительные поля в классе, который предназначен для парсинга. Эти поля нужны только для отображения
- сам класс, который нужен для парсинга, отображается в пользовательском интерфейсе
- отображение результатов теперь работает только для одного режима парсинга

1. Для отображения лучше сделать новый объект.
2. То, что раньше писалось в System.out лучше накапливать в каком-то новом объекте (том же, что и пункт 1? не знаю)
3. Класс парсинга ничего не должен знать про GUI.

И ещё раз повторю - лучше делать одно изменение за один pull request. Для каждого изменения можно заводить новую ветку. Сейчас получилось так, что в master есть несколько недоделанных фич - это не круто.

2017-10-31 19:04 UTC, merged