issue 6
Morvell/liquid-log pull request #9
Opened 2017-11-29 15:31 UTC by Morvell

Вроде бы сделал. Однако отвалились тесты, но если всё правильно в решении, то я их переделаю.
@ykalemi @d0k1

2017-11-30 06:46 UTC, ykalemi requested changes
Только в конце понял, что это коммиты по заданию "Каждый DataParser -> Spring Bean". Тогда надо доделать части про spring bean и про пасреры. Generics это уже к следующей задаче

2017-11-30 06:46 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ParserController.java
> +        new Parser().parse(influxDAO, parserDate);
С одной стороны, Parser объявлен как `@Component`, с другой - здесь он создаётся через new. Надо выбрать что-то одно (и лучше бы это был spring-way)

2017-11-30 06:46 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/sdng/SdngData.java
> +        actionsDone = new ActionDoneParser();
хочется, чтобы вы пошли до конца и разорвали эту странную мешанину парсеров и данных. ActionDoneParser и ErrorParser - тоже парсеры. Но хранят в себе данные. Хочется, чтобы к ним были применены все те же правила, что и к остальным парсерам

2017-11-30 06:46 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/sdng/SdngDataParser.java
> +    public void parseLine(IData data, String line) {
В задании я писал про Generics, посмотрите возможные применения в интерфейсах и реализациях. Нужно сделать так, чтобы, например, в этом конкретном классе метод выглядел так:
`public void parseLine(ISdngData data, String line)`
т.е. не нужно было бы делать каст

https://en.wikipedia.org/wiki/Generics_in_Java

2017-12-16 16:47 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/sdng/SdngData.java
> +        actionsDone = new ActionDoneParser();
еще вот этот момент хочу чтобы вы исправили

2017-12-17 11:25 UTC, ykalemi commented
В целом - ок, теперь можно и тесты исправить

2017-12-18 07:53 UTC, ykalemi approved these changes

2017-12-18 07:53 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/sdng/SdngDataParser.java
> +        new ActionDoneParser().parseLine(sdngData.getActionsDone(),line);
на каждую строку создаете два новых объекта

2017-12-18 09:00 UTC, Morvell commented
@ykalemi Я допущен до зачета, или нужно еще доделать?

2017-12-18 09:14 UTC, ykalemi commented
Допущены

2017-12-18 16:10 UTC, merged